### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by andrewromanenco** [andrewromanenco/pyjvm#5]
I am opening this issue to share some idea to be implemented for the project

**Comment by wgaylord** [comment]
Hi and okay.

**Comment by andrewromanenco** [comment]
Hi

I see two major directions:
1. Have better virtual machine.
   Because of historical reasons, current code is not design to its best. So it's possible to improve it and, also, migrate to python 3.
   The biggest problem is reasoning: hard to answer to question "why?"
   The code is very slow. Also it's is complex, because it uses rt.jar from oracle sdk. Which means a lot of native code to be implemented. It's not design complexity, just lost of stuff has to be rewritten in python,
2. Better integration.
   Create a library to allow a python program to execute java class file: load it and run as a single threaded mini-app. challenge here is to provide implementations for all standard java classes.
   This project is easier, it's still has to have byte code loader, interpreter and may leverage garbage collector from python.
   To make the process continuous, it's possible to implement only several java core classes for the beginning (e.g. ArrayList, HashMap, HashSet). And have a clean mechanism how more java coverage can be added.

Please, let me know what do you think. thanks!

**Comment by wgaylord** [comment]
Well the second direction is a better one. And also one thing to say. If we just implement what is written in C of the JVM we can just use the normal java parts to complete it. Also one other thing. Yes python 3 is better but I was planing on using python 2.7 as that is what is on my ipad. (I mostly used this to run simple programs on my ipad from pythonista.  But honestly python 3 is why better.

**Comment by andrewromanenco** [comment]
@chibill let's see after new year (I am leaving to a vacation very soon)

I see no problem in supporting both python2 and 3

**Comment by wgaylord** [comment]
Okay.

**Comment by wgaylord** [comment]
I might try to working on bring the current pyjvm up more with more implemented ops,

**Comment by wgaylord** [comment]
Any idea if this will ever happen?
Right now I am adding in new native parts using information from  http://hg.openjdk.java.net/jdk6/jdk6/jdk/file/ac1d168048bd/src/

**Comment by andrewromanenco** [comment]
work-in-progress for new version with better design

**Comment by wgaylord** [comment]
Okay

**Comment by wgaylord** [comment]
Nice!

**Comment by wgaylord** [comment]
Did not want to open an issue to just say a suggestion. You could take advantage of https://github.com/TkTech/Jawa so you don't have to define as much stuff.

But not sure that's an option anymore now that your so far along in the project.

**Comment by andrewromanenco** [comment]
Hi, sorry for very late response. That code looks nice, but I think the one in repo is good enough.

p.s.
I am a bit overloaded at the moment; but still going to deliver core features to this project

tnx

**Comment by wgaylord** [comment]
It's fine. I mostly been following this project because it looks fun. 

(On a side note I have need working on a Java to Python translator by using the Java byte code.

**Comment by andrewromanenco** [comment]
That's a great idea!; if you have Java2Python, it means you have AlmostEverythingToPython (as most languages have compilers to bytecode). Would be cool to design the code so the actual code generation to be replaceable (as a plugin or a module).

**Comment by wgaylord** [comment]
I was planing on trying to do just byte code conversion.
